//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;
using System;
    
namespace ReportServiceReference {

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportServiceReference.ReportServiceSoap")]
    public interface ReportServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 filebytes 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload", ReplyAction="*")]
        ReportServiceReference.UploadResponse Upload(ReportServiceReference.UploadRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 filename 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownLoad", ReplyAction="*")]
        ReportServiceReference.DownLoadResponse DownLoad(ReportServiceReference.DownLoadRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetTemplateListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTemplateList", ReplyAction="*")]
        ReportServiceReference.GetTemplateListResponse GetTemplateList(ReportServiceReference.GetTemplateListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Upload", Namespace="http://tempuri.org/", Order=0)]
        public ReportServiceReference.UploadRequestBody Body;
        
        public UploadRequest() {
        }
        
        public UploadRequest(ReportServiceReference.UploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] filebytes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        public UploadRequestBody() {
        }
        
        public UploadRequestBody(byte[] filebytes, string filename) {
            this.filebytes = filebytes;
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadResponse", Namespace="http://tempuri.org/", Order=0)]
        public ReportServiceReference.UploadResponseBody Body;
        
        public UploadResponse() {
        }
        
        public UploadResponse(ReportServiceReference.UploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UploadResult;
        
        public UploadResponseBody() {
        }
        
        public UploadResponseBody(bool UploadResult) {
            this.UploadResult = UploadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoad", Namespace="http://tempuri.org/", Order=0)]
        public ReportServiceReference.DownLoadRequestBody Body;
        
        public DownLoadRequest() {
        }
        
        public DownLoadRequest(ReportServiceReference.DownLoadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public DownLoadRequestBody() {
        }
        
        public DownLoadRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadResponse", Namespace="http://tempuri.org/", Order=0)]
        public ReportServiceReference.DownLoadResponseBody Body;
        
        public DownLoadResponse() {
        }
        
        public DownLoadResponse(ReportServiceReference.DownLoadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownLoadResult;
        
        public DownLoadResponseBody() {
        }
        
        public DownLoadResponseBody(byte[] DownLoadResult) {
            this.DownLoadResult = DownLoadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTemplateListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTemplateList", Namespace="http://tempuri.org/", Order=0)]
        public ReportServiceReference.GetTemplateListRequestBody Body;
        
        public GetTemplateListRequest() {
        }
        
        public GetTemplateListRequest(ReportServiceReference.GetTemplateListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTemplateListRequestBody {
        
        public GetTemplateListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTemplateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTemplateListResponse", Namespace="http://tempuri.org/", Order=0)]
        public ReportServiceReference.GetTemplateListResponseBody Body;
        
        public GetTemplateListResponse() {
        }
        
        public GetTemplateListResponse(ReportServiceReference.GetTemplateListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTemplateListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportServiceReference.ArrayOfString GetTemplateListResult;
        
        public GetTemplateListResponseBody() {
        }
        
        public GetTemplateListResponseBody(ReportServiceReference.ArrayOfString GetTemplateListResult) {
            this.GetTemplateListResult = GetTemplateListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportServiceSoapChannel : ReportServiceReference.ReportServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceSoapClient : System.ServiceModel.ClientBase<ReportServiceReference.ReportServiceSoap>, ReportServiceReference.ReportServiceSoap {
        
        public ReportServiceSoapClient() {
        }
        
        public ReportServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportServiceReference.UploadResponse ReportServiceReference.ReportServiceSoap.Upload(ReportServiceReference.UploadRequest request) {
            return base.Channel.Upload(request);
        }
        
        public bool Upload(byte[] filebytes, string filename) {
            ReportServiceReference.UploadRequest inValue = new ReportServiceReference.UploadRequest();
            inValue.Body = new ReportServiceReference.UploadRequestBody();
            inValue.Body.filebytes = filebytes;
            inValue.Body.filename = filename;
            ReportServiceReference.UploadResponse retVal = ((ReportServiceReference.ReportServiceSoap)(this)).Upload(inValue);
            return retVal.Body.UploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportServiceReference.DownLoadResponse ReportServiceReference.ReportServiceSoap.DownLoad(ReportServiceReference.DownLoadRequest request) {
            return base.Channel.DownLoad(request);
        }
        
        public byte[] DownLoad(string filename) {
            ReportServiceReference.DownLoadRequest inValue = new ReportServiceReference.DownLoadRequest();
            inValue.Body = new ReportServiceReference.DownLoadRequestBody();
            inValue.Body.filename = filename;
            ReportServiceReference.DownLoadResponse retVal = ((ReportServiceReference.ReportServiceSoap)(this)).DownLoad(inValue);
            return retVal.Body.DownLoadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportServiceReference.GetTemplateListResponse ReportServiceReference.ReportServiceSoap.GetTemplateList(ReportServiceReference.GetTemplateListRequest request) {
            return base.Channel.GetTemplateList(request);
        }
        
        public ReportServiceReference.ArrayOfString GetTemplateList() {
            ReportServiceReference.GetTemplateListRequest inValue = new ReportServiceReference.GetTemplateListRequest();
            inValue.Body = new ReportServiceReference.GetTemplateListRequestBody();
            ReportServiceReference.GetTemplateListResponse retVal = ((ReportServiceReference.ReportServiceSoap)(this)).GetTemplateList(inValue);
            return retVal.Body.GetTemplateListResult;
        }
    }
}
